# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20160826_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='did_have_snapshot',
            field=models.BooleanField(default=False),
        ),
    ]
