# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_two_factor_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectcommand',
            name='name',
            field=models.CharField(help_text='Name of your custom command.', max_length=128, verbose_name='name'),
        ),
    ]
