# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170707_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disk_snapshot_limit',
            field=models.IntegerField(default=3, help_text='Snapshot limit per disk.', verbose_name='disk snapshot limit'),
        ),
    ]
