# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170707_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='network_limit',
            field=models.IntegerField(default=2, verbose_name=b'Virtual network limit'),
        ),
    ]
