# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:09
from __future__ import unicode_literals

from django.db import migrations
import firewall.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0005_auto_20150520_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ipv6',
            field=firewall.fields.IPAddressField(blank=True, help_text='The global IPv6 address of the host, for example 2001:db:88:200::10.', null=True, unique=True, verbose_name='IPv6 address', version=6),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='network6',
            field=firewall.fields.IPNetworkField(blank=True, help_text='The IPv6 address and the prefix length of the gateway.', null=True, verbose_name='IPv6 address/prefix', version=6),
        ),
    ]
